ORI_dataset_path: /home/adev/yolov4-container/dataset
YOLO_darknet_path: /home/adev/yolov4-container/darknet
project_name: pcb_512
input_dataset_path: /home/adev/yolov4-container/dataset/pcb_512
YOLO_config_path: /home/adev/yolov4-container/YOLO_train/cfg
YOLO_weight_path: /home/adev/yolov4-container/YOLO_train/weights
YOLO_dataset_path: /home/adev/yolov4-container/YOLO_train/yolov4_dataset
YOLO_inference_path: /home/adev/yolov4-container/YOLO_train/result
TRAIN_data_path: /home/adev/yolov4-container/YOLO_train/yolov4_dataset/train_data
VAL_data_path: /home/adev/yolov4-container/YOLO_train/yolov4_dataset/valid_data
TEST_data_path: /home/adev/yolov4-container/YOLO_train/yolov4_dataset/test_data
yolov4_model_file_path: /home/adev/yolov4-container/YOLO_train/cfg/yolov4_2022_01_03.weights
yolov4_best_model: /home/adev/yolov4-container/YOLO_train/cfg/pcb_512_final_2022-04-25.weights
set_ratio: '0.6'
batch: '4'
subdivisions: '4'
width: '512'
height: '512'
channels: '3'
max_batches: '500500'
select_cfg: yolov4.cfg
Option_config: '0'
momentum: '-1'
decay: '-1'
angle: '-1'
saturation: '-1'
exposure: '-1'
hue: '-1'
learning_rate: '-1'
mosaic: '-1'
burn_in: '-1'
letter_box: -1
ema_alpha: -1
test_GT_csv: /home/adev/yolov4-container/YOLO_train/cfg/test_GT.csv
valid_GT_csv: /home/adev/yolov4-container/YOLO_train/cfg/valid_GT.csv
yolo_valid_csv: yolo_valid.csv
valid_eval_csv: /home/adev/yolov4-container/YOLO_train/result/valid_eval.csv
test_eval_csv: /home/adev/yolov4-container/YOLO_train/result/test_eval.csv
pretrained: /home/adev/yolov4-container/YOLO_train/cfg/yolov4_2022_01_03.weights
