ORI_dataset_path: /home/user/yolov4-container/dataset
YOLO_darknet_path: /home/user/yolov4-container/darknet
project_name: pcb_512
input_dataset_path: /home/user/yolov4-container/dataset/pcb_512
YOLO_config_path: /home/user/yolov4-container/YOLO_train/cfg
YOLO_weight_path: /home/user/yolov4-container/YOLO_train/weights
YOLO_dataset_path: /home/user/yolov4-container/YOLO_train/yolov4_dataset
YOLO_inference_path: /home/user/yolov4-container/YOLO_train/result
TRAIN_data_path: /home/user/yolov4-container/YOLO_train/yolov4_dataset/train_data
VAL_data_path: /home/user/yolov4-container/YOLO_train/yolov4_dataset/valid_data
TEST_data_path: /home/user/yolov4-container/YOLO_train/yolov4_dataset/valid_data
yolov4_best_model: /home/user/yolov4-container/YOLO_train/weights/tmp/1.weights
set_ratio: '0.6'
batch: '4'
subdivisions: '4'
width: '512'
height: '512'
channels: '3'
max_batches: '500500'
select_cfg: yolov4.cfg
learning_rate: '-1'
test_GT_csv: /home/user/yolov4-container/YOLO_train/cfg/test_GT.csv
valid_GT_csv: /home/user/yolov4-container/YOLO_train/cfg/valid_GT.csv
yolo_valid_csv: yolo_valid.csv
valid_eval_csv: /home/user/yolov4-container/YOLO_train/result/valid_eval.csv
test_eval_csv: /home/user/yolov4-container/YOLO_train/result/test_eval.csv
pretrained: /home/user/yolov4-container/YOLO_train/cfg/yolov4.conv.137
NMS_flag: '1'
NMS_Iou_threshold: '0.75'
Edge_limit: '10'
inference_Batch_size: '1'
Score_threshold: '0.001'
Iou_threshold: '0.1'
Precision: '0'
Recall: '0'
F1_score: '0'
